added --yeah and --nope cli args

diff --git a/ding b/ding
--- a/ding
+++ b/ding
@@ -1,8 +1,13 @@
 #!/bin/bash
-
-# Run the command and capture its exit code
-"$@"
-exit_code=$?
+if [[ "$1" = "--yeah" ]]; then
+    exit_code=0
+elif [[ "$1" = "--nope" ]]; then
+    exit_code=1
+else
+    # Run the command and capture its exit code
+    "$@"
+    exit_code=$?
+fi
 
 # depending on the platform, choose the right sound command
 if [[ "$OSTYPE" == "darwin"* ]]; then
